site_name: zMod - Firmware for AD5M / AD5MPro / AD5X
site_description: Complete documentation for ZMOD - FF5M / FF5M Pro / AD5X firmware modifications
site_author: ghzserg
repo_url: https://github.com/ghzserg/zmod
repo_name: ghzserg/zmod
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  language: en
  logo: images/logo.png
  favicon: images/fav.png
  icon:
    edit: material/pencil
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.action.edit
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark theme

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: light green
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

docs_dir: ../docs
site_dir: site

plugins:
  - search
  - i18n:
      reconfigure_material: true
      docs_structure: folder
      languages:
        - locale: cs
          name: ƒåe≈°tina
          build: true
          theme:
            language: cs
          nav_translations:
            Index: Domovsk√° str√°nka

            Begin: Zaƒç√°tek
            Setup: Nastaven√≠
            SetupCalibrations: Prvotn√≠ nastaven√≠ kalibrace
            Recommendations: Doporuƒçen√≠

            Configuration: Konfigurace
            Parameters: Parametry
            Plugins: Pluginy
            Telegram: Telegram

            Help: N√°povƒõda
            FAQ: FAQ

            Macros: Makra
            List: Seznam
            Main: Hlavn√≠ funkce
            Calibrations: Kalibrace
            Start/Stop/Global: Start/Stop/Glob√°ln√≠
            System: Syst√©m
            Filament: Filament

            Additional: Dodateƒçn√©
            Native firmware: Nativn√≠ firmware
            Changelog: Historie zmƒõn
            Support: Podpora

            Download: St√°hnout
            Video: Video
            TelegramBot: Telegram bot
            zModLink: zMod LINK
        - locale: en
          default: true
          name: English
          build: true
          reconfigure_search: true
          theme:
            language: en
          nav_translations:
            Index: Startseite

            Begin: Beginn
            Setup: Einrichtung
            SetupCalibrations: Ersteinrichtung Kalibrierung
            Recommendations: Empfehlungen

            Configuration: Konfiguration
            Parameters: Parameter
            Plugins: Plugins
            Telegram: Telegram

            Help: Hilfe
            FAQ: FAQ

            Macros: Makros
            List: Liste
            Main: Hauptfunktionen
            Calibrations: Kalibrierungen
            Start/Stop/Global: Start/Stopp/Globale
            System: System
            Filament: Filament

            Additional: Zus√§tzlich
            Native firmware: Native Firmware
            Changelog: √Ñnderungshistorie
            Support: Support

            Download: Herunterladen
            Video: Video
            TelegramBot: Telegram-Bot
            zModLink: zMod LINK
        - locale: ru
          name: –†—É—Å—Å–∫–∏–π
          build: true
          reconfigure_search: true
          theme:
            language: ru
          nav_translations:
            Index: –ì–ª–∞–≤–Ω–∞—è

            Begin: –ù–∞—á–∞–ª–æ
            Setup: –£—Å—Ç–∞–Ω–æ–≤–∫–∞
            Setup Calibrations: –ü–µ—Ä–≤–æ–Ω–∞—á–∞–ª—å–Ω–∞—è –∫–∞–ª–∏–±—Ä–æ–≤–∫–∞
            Recommendations: –†–µ–∫–æ–º–µ–Ω–¥–∞—Ü–∏–∏

            Configuration: –ù–∞—Å—Ç—Ä–æ–π–∫–∞
            Parameters: –ü–∞—Ä–∞–º–µ—Ç—Ä—ã
            Plugins: –ü–ª–∞–≥–∏–Ω—ã
            Telegram: –¢–µ–ª–µ–≥—Ä–∞–º

            Help: –ü–æ–º–æ—â—å 
            FAQ: FAQ

            Macros: –ú–∞–∫—Ä–æ—Å—ã
            List: –°–ø–∏—Å–æ–∫
            Main: –û—Å–Ω–æ–≤–Ω—ã–µ
            Calibrations: –ö–∞–ª–∏–±—Ä–æ–≤–∫–∏
            Start/Stop/Global: –°—Ç–∞—Ä—Ç/–°—Ç–æ–ø/–ì–ª–æ–±–∞–ª—å–Ω—ã–µ
            System: –°–∏—Å—Ç–µ–º–∞
            Filament: –§–∏–ª–∞–º–µ–Ω—Ç

            Additional: –î–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ
            Native firmware: –†–æ–¥–Ω–∞—è –ø—Ä–æ—à–∏–≤–∫–∞
            Changelog: –ò—Å—Ç–æ—Ä–∏—è –∏–∑–º–µ–Ω–µ–Ω–∏–π
            Support: –ü–æ–¥–¥–µ—Ä–∂–∫–∞

            Social: –°–æ—Ü—Å–µ—Ç–∏
            Download: –°–∫–∞—á–∞—Ç—å
            Video: –í–∏–¥–µ–æ
            TelegramBot: –¢–µ–ª–µ–≥—Ä–∞–º –±–æ—Ç
            zModLink: zMod LINK
        - locale: de
          name: Deutsch
          build: true
          reconfigure_search: true
          theme:
            language: de
          nav_translations:
            Index: Startseite

            Begin: Beginn
            Setup: Einrichtung
            Setup Calibrations: Ersteinrichtung Kalibrierung
            Recommendations: Empfehlungen

            Configuration: Konfiguration
            Parameters: Parameter
            Plugins: Plugins
            Telegram: Telegram

            Help: Hilfe
            FAQ: FAQ

            Macros: Makros
            List: Liste
            Main: Hauptfunktionen
            Calibrations: Kalibrierungen
            Start/Stop/Global: Start/Stopp/Globale
            System: System
            Filament: Filament

            Additional: Zus√§tzlich
            Native firmware: Native Firmware
            Changelog: √Ñnderungshistorie
            Support: Support

            Download: Herunterladen
            Video: Video
            TelegramBot: Telegram-Bot
            zModLink: zMod LINK
        - locale: pt
          name: Portugu√™s
          build: true
          search: true
          theme:
            language: pt
          nav_translations:
            Index: P√°gina inicial

            Begin: In√≠cio
            Setup: Instala√ß√£o
            Setup Calibrations: Calibra√ß√£o inicial
            Recommendations: Recomenda√ß√µes

            Configuration: Configura√ß√£o
            Parameters: Par√¢metros
            Plugins: Plugins
            Telegram: Telegram

            Help: Ajuda
            FAQ: Perguntas frequentes

            Macros: Macros
            List: Lista
            Main: Principais
            Calibrations: Calibra√ß√µes
            Start/Stop/Global: Iniciar/Parar/Global
            System: Sistema
            Filament: Filamento

            Additional: Adicional
            Native firmware: Firmware nativo
            Changelog: Hist√≥rico de altera√ß√µes
            Support: Suporte

            Download: Baixar
            Video: V√≠deo
            TelegramBot: Bot do Telegram
            zModLink: zMod LINK

nav:
  - Index: index.md

  - Begin:
      - Setup: Setup.md
      - Setup Calibrations: SetupCalibrations.md
      - Recommendations: Recomendations.md

  - Configuration:
      - Setup Calibrations: SetupCalibrations.md
      - AD5X: AD5X.md
      - Plugins: Plugin.md
      - Telegram: Telegram.md

  - Help:
      - FAQ: FAQ.md
      - Help: Help.md

  - Macros:
      - List: Macros.md
      - Main: Main.md
      - Calibrations: Calibrations.md
      - Start/Stop/Global: Global.md
      - System: System.md
      - Zmod: Zmod.md
      - Filament: Filament.md
      - PRO: Pro.md

  - Additional:
      - Native firmware: Native_FW.md
      - Changelog: Changelog.md
      - Support: Sponsor.md

  - Social: Social.md
  - Download: https://github.com/ghzserg/zmod/releases/latest
  - Video: Video.md
  - zmod_help_bot: http://t.me/zmod_help_bot
  - zMod LINK: https://zmod.link/link/

extra:
  generator: false
  social:
    - icon: material/robot
      link: https://t.me/zmod_help_bot
      name: "Help Bot"
    - icon: fontawesome/brands/telegram
      link: https://t.me/zmod_info
      name: "Official Telegram Info Channel"
    - icon: fontawesome/brands/telegram
      link: https://t.me/FF_5M_5M_Pro/408369
      name: "Official Telegram Group"
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/1526322885078508
      name: "Unofficial Facebook Group"
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Cw4cT5C24q
      name: "Unofficial Discord Server"
    - icon: fontawesome/brands/github
      link: https://github.com/ghzserg/zmod
      name: "GitHub Repository"

extra_javascript:
  - /assets/js/external-links.js
  # - /assets/js/header-download.js

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
  - admonition
  - tables
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
          unicode: true
  - codehilite


copyright: Copyright &copy; 2024-2026 zMod development by <a href="https://github.com/ghzserg" target="_blank" rel="noopener">@ghzserg</a> üöÄ<br>Web page created with ‚ù§Ô∏è by <a href="https://github.com/xyzroe" target="_blank" rel="noopener">@xyzroe</a>
